In [1]:
import os
import pandas as pd
from pystac_client import Client
import geopandas as gpd
from shapely.geometry import Point, Polygon
from lonboard import viz

## Connect to Montandon STAC

In [2]:
STAC_API_URL = "https://montandon-eoapi.ifrc.org/stac"
API_TOKEN = os.getenv('MONTANDON_API_TOKEN')

In [3]:
auth_headers = {"Authorization": f"Bearer {API_TOKEN}"}

### Check Auth

In [4]:
# Connect to STAC API with authentication
try:
    client = Client.open(STAC_API_URL, headers=auth_headers)
    print(f"\n[OK] Connected to: {STAC_API_URL}")
    print(f"[OK] API Title: {client.title}")
    print(f"[OK] Authentication: Bearer Token (OpenID Connect)")
except Exception as e:
    print(f"\n[ERROR] Authentication failed: {e}")

[OK] Connected to: https://montandon-eoapi.ifrc.org/stac
[OK] API Title: Montandon STAC API
[OK] Authentication: Bearer Token (OpenID Connect)

In [5]:
client

## Fetch most recent Events

List collections with event items, usig simple string-matching on the collection id

In [6]:
collections_list = list(client.get_collections())

In [7]:
events_collection = [c for c in collections_list if '-events' in c.id]

In [8]:
for col in events_collection:
    print(f"{col.title} | {col.id}")

DesInventar Mapped Events | desinventar-events
EM-DAT Source Events | emdat-events
GDACS Source Events | gdacs-events
GFD Source Events | gfd-events
GLIDE Source Events | glide-events
IBTrACS Source Events | ibtracs-events
IDMC GIDD Source Events | idmc-gidd-events
IDMC Internal Displacement Updates (IDU) Impacts | idmc-idu-events
IFRC Source Events | ifrcevent-events
PDC Source Events | pdc-events
USGS Events | usgs-events

### Earthquakes: Single Collection Search
Search a single collection for the most earthquakes from USGS that have a magnitude > 5

In [9]:
search_earthquakes = client.search(
    collections=["usgs-events"],
    max_items=1000
)
items_earthquakes = list(search_earthquakes.items())

In [10]:
# Get the shape of an item
items_earthquakes[0]

In [11]:
# Build dataframe, sort by chronological order
gdf = gpd.GeoDataFrame(
    [{
        'id': item.id,
        'monty_corr_id': item.properties['monty:corr_id'],
        'datetime': pd.to_datetime(item.properties['datetime']),
        'title': item.properties['title'],
        'magnitude': item.properties['eq:magnitude'],
        'geometry': Point(item.geometry['coordinates'])
    } for item in items_earthquakes
    ]
).sort_values('datetime', ascending=False)

In [12]:
earthquakes = gdf[gdf['magnitude'] > 5]
earthquakes

,id,monty_corr_id,datetime,title,magnitude,geometry
54,usgs-event-us6000sykw,20260518-BRA-321294-GH0311-1-GCDB,2026-05-18 18:50:00.309000+00:00,M 5.3 - Bouvet Island region,5.3,POINT (-1.2672 -54.2795)
116,usgs-event-us6000syik,20260518-UNK-1031047-GH0311-1-GCDB,2026-05-18 13:44:26.230000+00:00,"M 5.1 - 26 km NW of Liuzhou, China",5.1,POINT (109.2073 24.4799)
215,usgs-event-us6000syh2,20260518-GRL-553872-GH0311-1-GCDB,2026-05-18 07:34:30.448000+00:00,M 5.2 - Mid-Indian Ridge,5.2,POINT (74.2599 -28.5299)
254,usgs-event-us6000syg1,20260518-UNK-418088-GH0311-1-GCDB,2026-05-18 02:10:41.745000+00:00,M 5.4 - West Chile Rise,5.4,POINT (-82.4593 -43.4009)
255,usgs-event-us6000syg0,20260518-UNK-957182-GH0311-1-GCDB,2026-05-18 02:05:24.327000+00:00,"M 5.2 - 36 km SSE of Syriam, Burma (Myanmar)",5.2,POINT (96.3164 16.4431)
411,usgs-event-us6000syc2,20260517-UNK-1268887-GH0311-1-GCDB,2026-05-17 08:04:17.461000+00:00,"M 5.4 - 84 km ENE of Severo-Kuril’sk, Russia",5.4,POINT (157.2919 50.8582)
413,usgs-event-us6000syby,20260517-UNK-784640-GH0311-1-GCDB,2026-05-17 07:51:56.627000+00:00,"M 5.1 - 109 km SSE of Lorengau, Papua New Guinea",5.1,POINT (147.7681 -2.8876)
547,usgs-event-us6000sy90,20260516-UNK-649747-GH0311-1-GCDB,2026-05-16 15:58:04.288000+00:00,"M 5.4 - 92 km E of Port-Vila, Vanuatu",5.4,POINT (169.1752 -17.8726)
556,usgs-event-us6000sy8k,20260516-UNK-732505-GH0311-1-GCDB,2026-05-16 15:17:56.098000+00:00,"M 5.7 - 33 km NE of Auki, Solomon Islands",5.7,POINT (160.9161 -8.5526)
558,usgs-event-us6000sy84,20260516-UNK-967195-GH0311-1-GCDB,2026-05-16 14:50:03.503000+00:00,"M 6.0 - 70 km ESE of Codrington, Antigua and B...",6.0,POINT (-61.1771 17.5127)
563,usgs-event-us6000sy7u,20260516-UNK-649747-GH0311-1-GCDB,2026-05-16 14:07:54.649000+00:00,"M 5.2 - 94 km E of Port-Vila, Vanuatu",5.2,POINT (169.2036 -17.7708)
572,usgs-event-us6000sy7l,20260516-UNK-649747-GH0311-1-GCDB,2026-05-16 12:59:30.959000+00:00,"M 5.3 - 94 km E of Port-Vila, Vanuatu",5.3,POINT (169.1937 -17.8503)
809,usgs-event-us6000sxwq,20260515-UNK-1160812-GH0311-1-GCDB,2026-05-15 11:22:01.649000+00:00,"M 6.7 - 49 km ESE of Ōfunato, Japan",6.7,POINT (142.2498 38.9127)
959,usgs-event-us6000sxu9,20260515-UNK-782840-GH0311-1-GCDB,2026-05-15 01:13:58.659000+00:00,"M 5.4 - 119 km SSE of Lorengau, Papua New Guinea",5.4,POINT (147.7607 -2.9915)

In [13]:
print(f"There have been {len(earthquakes)} recent earthquakes with a magnitude > 5, with {len(earthquakes['monty_corr_id'].unique())} Montandon correlation IDs.")

There have been 14 recent earthquakes with a magnitude > 5, with 12 Montandon correlation IDs.

### Visualize Shakemaps

In [14]:
corr_ids = earthquakes['monty_corr_id'].unique().tolist()

In [15]:
hazard_filter = {
    "op": "or",
    "args": [
        {
            "op": "=",
            "args": [
                {"property": "monty:corr_id"},
                corr_id,
            ],
        }
        for corr_id in corr_ids
    ],
}

In [16]:
search_hazards = client.search(
    collections=["usgs-hazards"],
    filter_lang="cql2-json",
    filter=hazard_filter,
    max_items=10,
)

In [17]:
earthquake_hazards = list(search_hazards.items())

In [25]:
from shapely.geometry import shape

hazard_rows = []
for item in earthquake_hazards:
    props = item.properties
    geom = shape(item.geometry) if item.geometry else None
    if geom and (geom.is_empty or geom.area == 0):
        continue
    hazard_rows.append({
        "id": item.id,
        "monty_corr_id": props.get("monty:corr_id"),
        "src_event_id": props.get("monty:src_event_id"),
        "title": props.get("title"),
        "datetime": props.get("datetime"),
        'magnitude': item.properties['eq:magnitude'],
        "geometry": geom,
    })
hazards_gdf = gpd.GeoDataFrame(hazard_rows, crs="EPSG:4326", geometry="geometry")

In [26]:
hazards_gdf

,id,monty_corr_id,src_event_id,title,datetime,magnitude,geometry
0,usgs-hazard-us6000syg1-shakemap,20260518-UNK-418088-GH0311-1-GCDB,us6000syg1,M 5.4 - West Chile Rise,2026-05-18T02:10:41.745000Z,5.4,"POLYGON ((-84.983 -45.167, -80.05 -45.167, -80..."
1,usgs-hazard-us6000syg0-shakemap,20260518-UNK-957182-GH0311-1-GCDB,us6000syg0,"M 5.2 - 36 km SSE of Syriam, Burma (Myanmar)",2026-05-18T02:05:24.327000Z,5.2,"POLYGON ((94.45 14.633, 98.217 14.633, 98.217 ..."
2,usgs-hazard-us6000syc2-shakemap,20260517-UNK-1268887-GH0311-1-GCDB,us6000syc2,"M 5.4 - 84 km ENE of Severo-Kuril’sk, Russia",2026-05-17T08:04:17.461000Z,5.4,"POLYGON ((154.567 49.017, 160.25 49.017, 160.2..."
3,usgs-hazard-us6000sy90-shakemap,20260516-UNK-649747-GH0311-1-GCDB,us6000sy90,"M 5.4 - 92 km E of Port-Vila, Vanuatu",2026-05-16T15:58:04.288000Z,5.4,"POLYGON ((167.267 -19.65, 171.05 -19.65, 171.0..."
4,usgs-hazard-us6000sy8k-shakemap,20260516-UNK-732505-GH0311-1-GCDB,us6000sy8k,"M 5.7 - 33 km NE of Auki, Solomon Islands",2026-05-16T15:17:56.098000Z,5.7,"POLYGON ((159.083 -10.333, 162.733 -10.333, 16..."
5,usgs-hazard-us6000sy84-shakemap,20260516-UNK-967195-GH0311-1-GCDB,us6000sy84,"M 6.0 - 70 km ESE of Codrington, Antigua and B...",2026-05-16T14:50:03.503000Z,6.0,"POLYGON ((-63.033 15.7, -59.25 15.7, -59.25 19..."

In [27]:
viz(hazards_gdf)

VBox(children=(<lonboard._map.Map object at 0x11bf1d090>, VBox(children=(ErrorOutput(), ErrorOutput()), layout…